resource_group_name   = "myResourceGroup123"
app_service_plan_name = "myAppServicePlan"
backend_app_name      = "mybackendapp12345"
frontend_app_name     = "myfrontendapp12345"
acr_login_server      = "acrtestunique1234567.azurecr.io"
backend_image         = "backend"
frontend_image        = "frontend"
acr_name              = "acrtestunique1234567"
