name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*'

env:
  ACR_LOGIN_SERVER: acrtestunique1234567.azurecr.io
  RESOURCE_GROUP_NAME: myResourceGroup123
  APP_SERVICE_PLAN_NAME: myAppServicePlan
  BACKEND_APP_NAME: mybackendapp12345
  FRONTEND_APP_NAME: myfrontendapp12345
  ACR_NAME: acrtestunique1234567
  BACKEND_IMAGE: backend
  FRONTEND_IMAGE: frontend

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build test environment
        run: docker-compose -f docker-compose.test.yml build
      
      - name: Run tests
        run: bash run-test.sh

  build-push-latest:
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push latest images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  build-push-tagged:
    runs-on: ubuntu-latest
    needs: run-tests
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Extract version tag
        id: extract_version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Build and push versioned images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
        env:
          BACKEND_IMAGE_TAG: ${{ env.TAG_VERSION }}
          FRONTEND_IMAGE_TAG: ${{ env.TAG_VERSION }}

  deploy-infrastructure:
    runs-on: ubuntu-latest
    needs: build-push-tagged
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        working-directory: infra/deployment
        run: terraform init
      
      - name: Terraform Apply
        working-directory: infra/deployment
        run: terraform apply -auto-approve
        env:
          TF_VAR_resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
          TF_VAR_app_service_plan_name: ${{ env.APP_SERVICE_PLAN_NAME }}
          TF_VAR_backend_app_name: ${{ env.BACKEND_APP_NAME }}
          TF_VAR_frontend_app_name: ${{ env.FRONTEND_APP_NAME }}
          TF_VAR_acr_login_server: ${{ env.ACR_LOGIN_SERVER }}
          TF_VAR_backend_image: ${{ env.BACKEND_IMAGE }}
          TF_VAR_backend_image_tag: ${{ env.TAG_VERSION }}
          TF_VAR_frontend_image: ${{ env.FRONTEND_IMAGE }}
          TF_VAR_frontend_image_tag: ${{ env.TAG_VERSION }}
          TF_VAR_acr_name: ${{ env.ACR_NAME }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}